### ISSUE TITLE
Multiple Instances of api

### ISSUE THREAD

**Issue by brad-decker** [ideaoforder/bigcommerce_api#4]
Hey, 

beings as it appears that the initialize method of Base is simply changing variables attached to the class, how can we reliably use the api in an application type context where there are multiple users all with their own access_tokens, etc?

I was hoping that we could instantiate the api and access it like such api = BigcommerceAPI::Base.new(parameters_here)
then access each endpoint specific to the user's context like api.product.all, etc ..

What would be the proper way to utilize this gem efficiently in a rails app where multiple users might be utilizing functions of the bigcommerce api simultaneously?

**Comment by ideaoforder** [comment]
My understanding is that the class is instantiated within the current Ruby process. So, if you have two users who are making concurrent requests, then either (a) they're handled by separate Ruby processes (most production apps will have several), or (b) they are processed in order.

You're concern here is a valid one--you are essentially leaving an open connection (which in this case, really just means that you're keeping a set of connection params tied to the Base class). We handle this by re-initializing the connection before every request or series of requests. Our rule of thumb is to create an instance in each method--that method might then make several requests for the same shop.

Creating a new connection within the same process effectively severs the previous connection (you're just changing the params associated with the Base class). 

We have this running both in-app, with multiple processes, as well as in an hourly rake task (1 process that hits lots of stores in sequence), and both work fine.

That being said, if you're interested in writing a block method to wrap requests in a safer way, I'd be glad to have it, and would happily pull a working fork. Maybe a new method very similar to the 'initialize' method in the Base class?

I realize this thread's a bit old, so you've perhaps moved on, or possibly solved this already.

I'm closing this out, but again, would love to see a fork.
