### ISSUE TITLE
Getting store info?

### ISSUE THREAD

**Issue by hajrice** [ideaoforder/bigcommerce_api#6]
Hi, 

I've been struggling for hours.

Any documentation/tips on getting the store info?

**Comment by ideaoforder** [comment]
My apologies--I added in the ability to get store info a little while ago, but never updated the documentation (which I now have).

You can get it directly from the connection:

api = BigcommerceAPI::Base.new(
    :client_id => APP_CLIENT_ID,
    :store_hash => STORE_HASH/ID,
    :access_token => OAUTH_ACCESS_TOKEN
)
api.store

**Comment by hajrice** [comment]
Hmm,

THat's odd, I get some odd error (http://d.pr/i/18TeT)

!! #<JSON::ParserError: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html> 	<head> 
                     (right here) ------^

Any ideas what this means?

**Comment by ideaoforder** [comment]
From that error, it looks like you're not hitting a proper store URL. It should return JSON, but you can see that it's returning HTML, which isn't valid. I can't tell what's in body[:context] but maybe that's the issue? Are you able to execute other requests?

**Comment by hajrice** [comment]
Hey Mark

Just wanted to ask
Any way we can create pages via the API?

On Tuesday, January 27, 2015, Mark Dickson <notifications@github.com> wrote:

> From that error, it looks like you're not hitting a proper store URL. It
> should return JSON, but you can see that it's returning HTML, which isn't
> valid. I can't tell what's in body[:context] but maybe that's the issue?
> Are you able to execute other requests?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ideaoforder/bigcommerce_api/issues/6#issuecomment-71752054>
> .
>


-- 
Sincerely,
Emil Hajric,
CEO, Helpjuice.com

*Office*: (888) 230-3420
*Cell*: 904-419-3645

Helpjuice, Inc.,
5 W Forsyth,
32202 Jacksonville, FL

**Comment by ideaoforder** [comment]
Hey Emil, 

At the moment there isn't, but if you want to fork the gem, it should be pretty clear from the other resources how to do it. 

Let me know if you've got any questions.

Cheers,
Mark
